name = "ak-web"
compatibility_date = "2026-03-22"
main = "src/worker/index.js"

[vars]
ALLOWED_USER_ID = "271658515"

[assets]
directory = "./dist"
binding = "ASSETS"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "ak-photos"

[[kv_namespaces]]
binding = "UPLOAD_STATE"
id = "05707b0dca0c4fa9847d318aa3e7b7f6"
